#!/bin/sh
# Deny git push when unpushed commits still contain Co-authored-by trailers.
set -e
input=$(python3 -c 'import json,sys; print(json.load(sys.stdin).get("command",""))')
case "$input" in
  *git\ push*)
    ;;
  *)
    echo '{ "permission": "allow" }'
    exit 0
    ;;
esac

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo '{ "permission": "allow" }'
  exit 0
fi

range="HEAD"
if git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
  range='@{u}..HEAD'
fi

if git log --format='%B' $range 2>/dev/null | grep -E -i -q \
  -e '^[[:space:]]*Co-authored-by:' \
  -e '^[[:space:]]*Made-with:' \
  -e '^[[:space:]]*Made with ' \
  -e '^[[:space:]]*Generated by'; then
  printf '%s\n' '{
    "permission": "deny",
    "user_message": "Push blocked: a commit still has a Co-authored-by trailer.",
    "agent_message": "Strip Co-authored-by from the commit before pushing. Do not use --no-verify."
  }'
  exit 0
fi

echo '{ "permission": "allow" }'
exit 0
