#!/bin/sh
# If the last git commit still has a Co-authored-by trailer, amend it out (unpushed only).
set -e
input=$(python3 -c 'import json,sys; print(json.load(sys.stdin).get("command",""))')
case "$input" in
  *git\ commit*)
    ;;
  *)
    echo '{}'
    exit 0
    ;;
esac

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo '{}'
  exit 0
fi

body=$(git log -1 --format=%B 2>/dev/null || true)
if ! printf '%s\n' "$body" | grep -E -i -q \
  -e '^[[:space:]]*Co-authored-by:' \
  -e '^[[:space:]]*Made-with:' \
  -e '^[[:space:]]*Made with ' \
  -e '^[[:space:]]*Generated by'; then
  echo '{}'
  exit 0
fi

if git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
  unpushed=$(git rev-list --count '@{u}..HEAD' 2>/dev/null || echo 1)
  if [ "$unpushed" = "0" ]; then
    echo '{}'
    exit 0
  fi
fi

printf '%s\n' "$body" | grep -v -E -i \
  -e '^[[:space:]]*Co-authored-by:' \
  -e '^[[:space:]]*Made-with:' \
  -e '^[[:space:]]*Made with ' \
  -e '^[[:space:]]*Generated by' \
  | git commit --amend --no-verify -F -

echo '{}'
