import { ReactNode } from '../../../../../node_modules/.pnpm/react@19.2.8/node_modules/react';
import { TextControlSize } from '../textControl';
import { ComboboxListStatus } from './SelectListbox';
import { SelectItem, SelectOption, SelectOptionGroup } from './selectOptions';
export type ComboboxSize = TextControlSize;
export type { ComboboxListStatus };
export type ComboboxFilter = 'auto' | 'manual' | 'off';
export type ComboboxProps = {
    options: readonly SelectItem[];
    value?: string | readonly string[];
    defaultValue?: string | readonly string[];
    onValueChange?: (value: string | string[]) => void;
    multiple?: boolean;
    name?: string;
    form?: string;
    placeholder?: string;
    emptyMessage?: ReactNode | ((query: string) => ReactNode);
    size?: ComboboxSize;
    label?: ReactNode;
    helper?: ReactNode;
    error?: ReactNode;
    invalid?: boolean;
    valid?: boolean;
    disabled?: boolean;
    required?: boolean;
    fullWidth?: boolean;
    className?: string;
    id?: string;
    clearable?: boolean;
    clearLabel?: string;
    toggleLabel?: string;
    chipGroupLabel?: string;
    chipRemoveLabel?: string;
    defaultOpen?: boolean;
    openOnFocus?: boolean;
    filter?: ComboboxFilter;
    onSearch?: (query: string) => void;
    listStatus?: ComboboxListStatus;
    loadingMessage?: string;
    listErrorMessage?: ReactNode;
    listErrorRetryMessage?: ReactNode;
    beforeOptions?: ReactNode;
    renderOption?: (option: SelectOption, selected: boolean) => ReactNode;
    renderSectionTitle?: (group: SelectOptionGroup) => ReactNode;
    renderChip?: (option: SelectOption) => ReactNode;
    icon?: ReactNode;
    'aria-label'?: string;
    'aria-labelledby'?: string;
    'aria-describedby'?: string;
};
export declare function Combobox({ options, value: valueProp, defaultValue, onValueChange, multiple, name, form, placeholder, emptyMessage, size, label, helper, error, invalid, valid, disabled, required, fullWidth, className, id, clearable, clearLabel, toggleLabel, chipGroupLabel, chipRemoveLabel, defaultOpen, openOnFocus, filter, onSearch, listStatus, loadingMessage, listErrorMessage, listErrorRetryMessage, beforeOptions, renderOption, renderSectionTitle, renderChip, icon, 'aria-label': ariaLabel, 'aria-labelledby': ariaLabelledBy, 'aria-describedby': ariaDescribedBy, }: ComboboxProps): import("react").JSX.Element;
