import { ReactNode } from '../../../../../node_modules/.pnpm/react@19.2.8/node_modules/react';
import { TextControlSize } from '../textControl';
import { SelectItem } from './selectOptions';
export type { SelectItem, SelectOption, SelectOptionGroup } from './selectOptions';
export type SelectSize = TextControlSize;
export type SelectProps = {
    options: readonly SelectItem[];
    value?: string;
    defaultValue?: string;
    onValueChange?: (value: string) => void;
    name?: string;
    form?: string;
    placeholder?: string;
    emptyMessage?: ReactNode;
    size?: SelectSize;
    label?: ReactNode;
    helper?: ReactNode;
    error?: ReactNode;
    invalid?: boolean;
    valid?: boolean;
    disabled?: boolean;
    required?: boolean;
    fullWidth?: boolean;
    className?: string;
    id?: string;
    'aria-label'?: string;
    'aria-labelledby'?: string;
    'aria-describedby'?: string;
};
export declare function Select({ options, value: valueProp, defaultValue, onValueChange, name, form, placeholder, emptyMessage, size, label, helper, error, invalid, valid, disabled, required, fullWidth, className, id, 'aria-label': ariaLabel, 'aria-labelledby': ariaLabelledBy, 'aria-describedby': ariaDescribedBy, }: SelectProps): import("react").JSX.Element;
